export const placeholderUrl = (text: string, width = 800, height = 500) =>
  `https://placehold.co/${width}x${height}/0c100d/f0f5f0?text=${encodeURIComponent(text).replace(/%20/g, '+')}`;

export const defaultHeroSlides = [
  {
    id: 'hero-0',
    imageUrl: '/images/desktop-banner-final.jpg',
    mobileImageUrl: '/images/mobile-banner-final.jpg',
    alt: 'Creanote Hero 1',
    title: 'Bright shares how curiosity shaped his path and what inspired him to continue',
    meta: 'CREANOTE FEATURE TIMELINE',
    badgeText: 'SPOTLIGHT',
    headline: 'Bright shares how curiosity shaped his path and what inspired him to continue',
    order: 0,
    isActive: true,
  },
  {
    id: 'hero-1',
    imageUrl: '/images/desktop-banner-final.jpg',
    mobileImageUrl: '/images/mobile-banner-final.jpg',
    alt: 'Creanote Hero 2',
    title: "3 creatives shared moments of their career they've never shared publicly.",
    meta: 'CREANOTE ANONYMOUS TIMELINE',
    badgeText: 'ANONYMOUS',
    headline: "3 creatives shared moments of their career they've never shared publicly.",
    order: 1,
    isActive: true,
  },
  {
    id: 'hero-2',
    imageUrl: '/images/desktop-banner-final.jpg',
    mobileImageUrl: '/images/mobile-banner-final.jpg',
    alt: 'Creanote Hero 3',
    title: 'Eesha shared what inspired her path into video editing, the challenges she faced, and the lessons she learned.',
    meta: 'CREANOTE FEATURE TIMELINE',
    badgeText: 'SPOTLIGHT',
    headline: 'Eesha shared what inspired her path into video editing, the challenges she faced, and the lessons she learned.',
    order: 2,
    isActive: true,
  },
  {
    id: 'hero-3',
    imageUrl: '/images/desktop-banner-final.jpg',
    mobileImageUrl: '/images/mobile-banner-final.jpg',
    alt: 'Creanote Hero 4',
    title: "This is your reminder that struggle doesn't mean failing, it means you're learning.",
    meta: 'CREANOTE QUOTE TIMELINE',
    badgeText: 'QUOTE',
    headline: "This is your reminder that struggle doesn't mean failing, it means you're learning.",
    order: 3,
    isActive: true,
  },
];

export const defaultTopItems = [
  {
    id: 'top-1',
    title: '"Just a hunger to make a living and take care of my…."',
    meta: 'STORYTELLER · 48 MONTHS',
    badgeText: '',
    badgeColor: 'orange' as const,
    imageUrl: placeholderUrl('Just a hunger to make a living', 800, 500),
    order: 0,
  },
  {
    id: 'top-2',
    title: "3 creatives shared moments they've never shared publicly.",
    meta: 'ANONYMOUS TIMELINE',
    badgeText: 'ANONYMOUS',
    badgeColor: 'orange' as const,
    imageUrl: placeholderUrl("3 creatives shared moments", 800, 500),
    order: 1,
  },
  {
    id: 'top-3',
    title: 'If you create, then you belong here. Click link in bio to get started.',
    meta: '',
    badgeText: 'CREANOTE',
    badgeColor: 'green' as const,
    imageUrl: placeholderUrl('If you create, you belong here', 800, 500),
    order: 2,
  },
];

export const defaultQuotes = [
  {
    id: 'quote-1',
    imageUrl: 'https://images.unsplash.com/photo-1550133730-695473e544be?q=80&w=800&auto=format&fit=crop',
    createdAt: '2026-01-21T10:00:00.000Z',
    isActive: true,
    order: 0,
  },
  {
    id: 'quote-2',
    imageUrl: 'https://images.unsplash.com/photo-1518655048521-f130df041f66?q=80&w=800&auto=format&fit=crop',
    createdAt: '2026-01-14T10:00:00.000Z',
    isActive: true,
    order: 1,
  },
  {
    id: 'quote-3',
    imageUrl: 'https://images.unsplash.com/photo-1493612276216-ee3925520721?q=80&w=800&auto=format&fit=crop',
    createdAt: '2026-01-08T10:00:00.000Z',
    isActive: true,
    order: 2,
  },
  {
    id: 'quote-4',
    imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=800&auto=format&fit=crop',
    createdAt: '2025-12-28T10:00:00.000Z',
    isActive: true,
    order: 3,
  },
];

export const defaultPosts = [
  {
    id: 'post-1',
    slug: '2-months-creator-shared-a-note-that-keep-her-going',
    date: 'JAN 21',
    headline: 'A creator shared a note that keeps her going.',
    sub: 'Faith Borntowin | 2 months + | Creator',
    category: 'CREATOR NOTE',
    author: 'Faith Borntowin',
    authorRole: 'Digital Creator (2 Months+)',
    readTime: '4 min read',
    coverImage: placeholderUrl('Creator note banner', 1200, 800),
    thumbUrl: placeholderUrl('Creator note', 640, 360),
    content:
      'When I started my creative journey 60 days ago, I genuinely felt that this industry was an exclusive club I was never invited to. Imposter syndrome did not just whisper; it shouted at every small mistake.\n\nWhat changed everything was shifting my mindset from "I must know everything" to "I only need to solve the very next step." Breaking big ideas into microscopic tasks, documenting daily milestones on Creanote, and reading authentic notes from creators who were once where I stood gave me the grit to keep going.\n\nIf you are on week two or month two: do not measure your beginning against someone else\'s fifth year. The struggle is the syllabus.',
    isFeatureBadge: false,
    featureText: '',
    page: 1,
    order: 0,
    isFeatured: true,
    isTopOnTheList: true,
  },
  {
    id: 'post-2',
    slug: 'if-you-create-this-space-is-for-you',
    date: 'JAN 14',
    headline: 'If you create, this space is for you. Get to know Creanote in 5 slides',
    sub: 'Have any other questions? Let us know in the comments or direct message',
    category: 'CREANOTE GUIDE',
    author: 'Creanote Editorial',
    authorRole: 'Community & Culture',
    readTime: '3 min read',
    coverImage: placeholderUrl('Creanote space banner', 1200, 800),
    thumbUrl: placeholderUrl('Creanote stories', 640, 360),
    content:
      'Creanote was created for one clear mission: to archive the raw, unedited, candid realities of building something from scratch.\n\n1. Transparent Journeys: Not just the victory laps, but the 3:00 AM creative blocks and pitch rejections.\n2. Visual Inspiration: High-signal quotes and reflections formatted to inspire focus.\n3. Collaborative Community: Direct insights from writers, artists, and visionaries.\n\nWhether you are designing a brand or launching your passion project, this is where your notes live.',
    isFeatureBadge: false,
    featureText: '',
    page: 1,
    order: 1,
    isTopOnTheList: true,
  },
  {
    id: 'post-3',
    slug: 'creanote-makes-link-for-story-sharing-live',
    date: 'JAN 23',
    headline: 'Creanote makes link sharing live on all platforms',
    sub: 'Creanote Update',
    category: 'PRODUCT UPDATE',
    author: 'Product Team',
    authorRole: 'HQ',
    readTime: '2 min read',
    coverImage: placeholderUrl('Story sharing feature banner', 1200, 800),
    thumbUrl: placeholderUrl('Story sharing feature', 640, 360),
    content:
      'Starting today, every creator on Creanote can generate personalized shareable links directly to their published notes and quotes.\n\nWith customized social preview cards, readers on your favorite platforms can preview your key quote before clicking through to read your full reflection.\n\nTry it now by clicking the Share button on any note in your archive.',
    isFeatureBadge: true,
    featureText: 'Creanote\nFeature',
    page: 1,
    order: 2,
    isTopOnTheList: true,
  },
  {
    id: 'post-4',
    slug: 'how-building-in-public-changed-my-creative-career',
    date: 'JAN 10',
    headline: 'How sharing my journey changed my creative career in 90 days.',
    sub: 'David Adeleke | Senior Creative | Storyteller',
    category: 'CASE STUDY',
    author: 'David Adeleke',
    authorRole: 'Senior Creative & Storyteller',
    readTime: '5 min read',
    coverImage: placeholderUrl('Sharing my journey banner', 1200, 800),
    thumbUrl: placeholderUrl('Sharing my journey', 640, 360),
    content:
      'For years, I operated in stealth mode. I waited until every paragraph was polished, every visual immaculate, and every piece of work beyond critique. The consequence? I rarely published anything.\n\n90 days ago, I committed to sharing works-in-progress on Creanote. The response was immediate: people resonated far more with the messy drafts and honest dilemmas than with the final polished piece.\n\nSharing my journey created accountability, opened doors to unexpected collaborations, and built genuine trust with an audience that cheered for the process, not just the outcome.',
    isFeatureBadge: false,
    featureText: '',
    page: 2,
    order: 3,
    isTopOnTheList: true,
  },
  {
    id: 'post-5',
    slug: 'unspoken-mental-barriers-every-self-taught-creator-encounters',
    date: 'JAN 05',
    headline: 'The unspoken mental barriers every self-taught creator encounters.',
    sub: 'Samuel Okewola | Digital Artist',
    category: 'MINDSET',
    author: 'Samuel Okewola',
    authorRole: 'Digital Artist',
    readTime: '6 min read',
    coverImage: placeholderUrl('Self taught creator banner', 1200, 800),
    thumbUrl: placeholderUrl('Self taught creator', 640, 360),
    content:
      'Being stuck in the learning phase is not a skill deficit; it is an anxiety response. When you lack a structured syllabus, every new tool or technique feels like proof that you do not know enough.\n\nThe breakthrough happened when I stopped collecting courses and started building small, flawed projects that solved real problems. You do not learn to swim by reading about water; you learn by jumping into the deep end and thrashing until your own rhythm emerges.',
    isFeatureBadge: false,
    featureText: '',
    page: 2,
    order: 4,
  },
  {
    id: 'post-6',
    slug: 'from-concept-to-live-project-lessons-in-perseverance',
    date: 'DEC 28',
    headline: 'From raw concept to a live project: lessons in perseverance.',
    sub: 'Abraham Isaiah | Digital Creator',
    category: 'CRAFT',
    author: 'Abraham Isaiah',
    authorRole: 'Digital Creator',
    readTime: '5 min read',
    coverImage: placeholderUrl('Concept to live project banner', 1200, 800),
    thumbUrl: placeholderUrl('Concept to live project', 640, 360),
    content:
      'Translating a rough idea with intricate details, delicate visuals, and fluid ideas into a finished product is a true testament to discipline.\n\nEvery small decision, spacing adjustment, and color choice matters. In this reflection, I detail the creative choices behind the scenes, the structure of the project, and the thoughtful patterns that make the final result feel incredibly natural to the audience.',
    isFeatureBadge: false,
    featureText: '',
    page: 3,
    order: 5,
  },
];
