export const defaultHeroSlides = [
  {
    id: 'hero-0',
    imageUrl: '/images/hero-0.jpg',
    alt: 'Creanote Hero 1',
    order: 0,
    isActive: true,
  },
  {
    id: 'hero-1',
    imageUrl: '/images/hero-1.jpg',
    alt: 'Creanote Hero 2',
    order: 1,
    isActive: true,
  },
  {
    id: 'hero-2',
    imageUrl: '/images/hero-2.jpg',
    alt: 'Creanote Hero 3',
    order: 2,
    isActive: true,
  },
  {
    id: 'hero-3',
    imageUrl: '/images/hero-3.jpg',
    alt: 'Creanote Hero 4',
    order: 3,
    isActive: true,
  },
];

export const defaultTopItems = [
  {
    id: 'top-1',
    title: '"Just a hunger to make money and take care of my…."',
    meta: 'COPYWRITER · 48 MONTHS',
    badgeText: '',
    badgeColor: 'orange' as const,
    imageUrl: '/images/top-card-1.jpg',
    order: 0,
  },
  {
    id: 'top-2',
    title: "3 creatives shared moments they've never shared publicly.",
    meta: 'ANONYMOUS TIMELINE',
    badgeText: 'ANONYMOUS',
    badgeColor: 'orange' as const,
    imageUrl: '/images/top-card-2.jpg',
    order: 1,
  },
  {
    id: 'top-3',
    title: 'If you create, then you belong here. Click link in bio to get started.',
    meta: '',
    badgeText: 'CREANOTE',
    badgeColor: 'green' as const,
    imageUrl: '/images/top-card-3.jpg',
    order: 2,
  },
];

export const defaultQuotes = [
  {
    id: 'quote-1',
    boldText: "Your current struggle isn't your permanent reality.",
    bodyText:
      "Don't be afraid to pivot your ideas or start over; the skills you learn in the failed attempts are what make the successful ones possible.",
    tagText: 'QUOTE',
    caption:
      "This is your reminder that struggle doesn't mean failing, it means you're learning.",
    credit: 'CREANOTE QUOTE TIMELINE',
    name: 'Software Developer',
    role: '@creanote_hq',
    avatarUrl: '/images/quote-avatar.jpg',
    isActive: true,
    order: 0,
  },
  {
    id: 'quote-2',
    boldText: 'The journey of a thousand commits begins with a single line.',
    bodyText:
      'Every great application you admire today once crashed on local machine. Consistency turns amateur effort into master craft.',
    tagText: 'INSPIRATION',
    caption: 'Keep pushing code, keep sharing notes, keep moving forward.',
    credit: 'CREANOTE CREATIVE COMMUNITY',
    name: 'UI/UX Designer',
    role: '@creanote_design',
    avatarUrl: '/images/quote-avatar.jpg',
    isActive: false,
    order: 1,
  },
  {
    id: 'quote-3',
    boldText: 'Authenticity resonates deeper than perfection ever could.',
    bodyText:
      'Do not wait until your story is without flaws to tell it. Your raw process is what inspires the next creator.',
    tagText: 'SPOTLIGHT',
    caption: 'Celebrate every small milestone in your creative journey.',
    credit: 'CREANOTE TIMELINE ARCHIVE',
    name: 'Product Strategist',
    role: '@creanote_build',
    avatarUrl: '/images/quote-avatar.jpg',
    isActive: false,
    order: 2,
  },
];

export const defaultPosts = [
  {
    id: 'post-1',
    date: 'JAN 21',
    headline: '2 months + dev shared a note that keep her going.',
    sub: 'Faith Borntowin | 2 months + | Developer',
    thumbUrl: '/images/post-1.jpg',
    isFeatureBadge: false,
    featureText: '',
    page: 1,
    order: 0,
  },
  {
    id: 'post-2',
    date: 'JAN 14',
    headline: 'If you create, this space if for you. Get to know creanote in 5 slides',
    sub: 'Have any other questions? Let us know in the comments or direct message',
    thumbUrl: '/images/post-2.jpg',
    isFeatureBadge: false,
    featureText: '',
    page: 1,
    order: 1,
  },
  {
    id: 'post-3',
    date: 'JAN 23',
    headline: 'Creanote makes link for story sharing live on their bio on all platforms',
    sub: 'Creanote Update',
    thumbUrl: '',
    isFeatureBadge: true,
    featureText: 'Creanote\nFeature',
    page: 1,
    order: 2,
  },
  {
    id: 'post-4',
    date: 'JAN 10',
    headline: 'How building in public changed my creative career in 90 days.',
    sub: 'David Adeleke | Senior Creative | Storyteller',
    thumbUrl: '/images/post-1.jpg',
    isFeatureBadge: false,
    featureText: '',
    page: 2,
    order: 3,
  },
  {
    id: 'post-5',
    date: 'JAN 05',
    headline: 'The unspoken mental barriers every self-taught programmer encounters.',
    sub: 'Samuel Okewola | Fullstack Developer',
    thumbUrl: '/images/post-2.jpg',
    isFeatureBadge: false,
    featureText: '',
    page: 2,
    order: 4,
  },
  {
    id: 'post-6',
    date: 'DEC 28',
    headline: 'From design mockup to live application: lessons in perseverance.',
    sub: 'Abraham Isaiah | Software Engineer',
    thumbUrl: '/images/post-1.jpg',
    isFeatureBadge: false,
    featureText: '',
    page: 3,
    order: 5,
  },
];
